app:
    resource: "@AppBundle/Controller/"
    type:     annotation

challenge:
    type: rest
    resource: '@AppBundle/Controller/PersonController.php'
    prefix:   /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
