app:
    resource: "@AppBundle/Controller/"
    type:     annotation

challenge:
    type: annotation
    resource: '@AppBundle/Controller/PersonController.php'

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
